language: python
sudo: false
dist: trusty

install:
    pip install gspread pyyaml oauth2client

script:
    # Build your program
    - echo "Building my program"
    - cat test.json | python stats-ci.py

#after_success:
    # Run Stats CI to log information related to the present build
    # Here there is an example on a possible input
    # The input can be also a JSON file on which you log information during the build operation
    
